### ISSUE TITLE
Semantic markup

### ISSUE THREAD

**Issue by ghost** [ross1979/ColmarAcademy#3]
https://github.com/ross1979/ColmarAcademy/blob/master/index.html#L13-L31

Nice job using `header`, `nav`, and `footer` here to make your markup more semantic.

Try to go the extra mile and add more semantic elements, like: `main`, `section`, `menu`, `figure`, etc. These can all make your markup a lot easier to read and reason about.

**Comment by ross1979** [comment]
Thanks for the additional feedback, i'll read up on the additional elements and addin.
